### ISSUE TITLE
Conda install of metamorpheus fails

### ISSUE THREAD

**Issue by erikj540** [smith-chem-wisc/MetaMorpheus#2503]
**Describing the issue**

Hello. Thanks for your help in advance!

I am on a Mac (with M3 processors) going through the ["Test Conda Installation..."](https://github.com/smith-chem-wisc/MetaMorpheus/wiki/Getting-Started#test-conda-installation-linux-macos-windows) instructions. 
I'm using conda v24.11.3. 
The `conda install -c conda-forge metamorpheus` fails with this output
```
$ conda install -c conda-forge metamorpheus
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - metamorpheus

Current channels:

  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/bioconda
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

I tried downloading the first `osx_*` `.conda` file from [here](https://anaconda.org/conda-forge/metamorpheus/files) and installing via `conda install metamorpheus-1.0.8-h6e16a3a_0.conda`. The install appears to work. But then running `metamorpheus -h" produces this error:
```
metamorpheus -h
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'CMD, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
/Users/erjo3868/miniforge3/envs/metamorpheus/bin/metamorpheus: line 3:  1669 Abort trap: 6           dotnet $DOTNET_TOOLS/metamorpheus/CMD.dll $@
```

Do you know why the `conda install` seems to be broken? Thank you!

**Comment by trishorts** [comment]
hmmmmm. not my area of expertise. i'm gonna reach out to someone that might be able to help. thanks for your patience.

**Comment by acesnik** [comment]
Hi there, I'm seeing a similar error on my side. I think it has something to do with `dotnet` not metamorpheus. Assuming you have also installed .NET 8 without conda (https://dotnet.microsoft.com/en-us/download/dotnet), could you double-check whether this errors out? 
`/usr/local/share/dotnet/dotnet $DOTNET_TOOLS/metamorpheus/CMD.dll -h`

This command works for me presently on mac, but the conda dotnet fails.

**Comment by acesnik** [comment]
Could you also run `/usr/local/share/dotnet/dotnet --list-runtimes`?

**Comment by acesnik** [comment]
If it does still error out with the `/usr/local/share/dotnet/dotnet` on arm64, we may need to explore building from source within conda (according to ChatGPT 😅 ):

```
source:
  git_url: https://github.com/smith-chem-wisc/MetaMorpheus.git
  git_rev: v{{ version }}

build:
  number: 1
  script:
    - dotnet publish MetaMorpheus.sln -c Release -r $TARGETPLATFORMRID --self-contained false -o $PREFIX/bin

requirements:
  build:
    - dotnet-sdk 8.*
    - {{ compiler('c') }}
    - {{ stdlib("c") }}

  run:
    - dotnet-runtime =8.0
```
